#!/usr/bin/env bash
#
# Put the Live Activity card on the booted simulator, fast.
#
# The card's design lives in `targets/live-activity/StillsLockScreenCard.swift`,
# which is Swift compiled into a widget extension — Metro cannot hot-reload it,
# and a full native build to see a padding change is a poor trade. This script
# compiles that one file into a throwaway host app and launches it, so the loop
# is about fifteen seconds and costs nothing.
#
# It renders every state at once — full, part-used, one left, none left,
# unlimited, a long event name — because the states that break a layout are
# rarely the one you were looking at.
#
# What this is NOT: a real Live Activity. There is no ActivityKit here, so it
# will not show you lock-screen behaviour, the Dynamic Island, or how the system
# clips the card's corners. For that you need a real build — see
# `npm run ios:local`. Use this for design, that for behaviour.
#
#   ./scripts/live-activity-preview.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CARD="$ROOT/targets/live-activity/StillsLockScreenCard.swift"
ASSETS="$ROOT/targets/live-activity/Assets.xcassets"
WORK="${TMPDIR:-/tmp}/stills-la-preview"
APP="$WORK/StillsLAPreview.app"
BUNDLE_ID="com.potoevents.stillslapreview"

if ! xcrun simctl list devices booted | grep -q "Booted"; then
  echo "No booted simulator. Open one first (Simulator.app, or 'xcrun simctl boot <udid>')." >&2
  exit 1
fi

echo "→ Building preview…"
rm -rf "$APP"
mkdir -p "$APP"

# The widget's own faces and asset catalogue, so the preview uses Cormorant Garamond and
# the real mark rather than falling back to a system serif and a blank square.
cp "$ROOT"/targets/live-activity/*.ttf "$APP/"
xcrun actool "$ASSETS" \
  --compile "$APP" \
  --platform iphonesimulator \
  --minimum-deployment-target 16.2 \
  --output-partial-info-plist /dev/null >/dev/null 2>&1

cat > "$WORK/main.swift" <<'SWIFT'
import SwiftUI

// Generated by scripts/live-activity-preview.sh. Not part of the app.

private struct Case: Identifiable {
    let id = UUID()
    let event: String
    let left: Int
    let allowance: Int?
    let endsIn: TimeInterval
}

private let cases: [Case] = [
    .init(event: "Priya and engagement", left: 24, allowance: 36, endsIn: 2 * 3600 + 90),
    .init(event: "Priya and engagement", left: 36, allowance: 36, endsIn: 26 * 3600),
    .init(event: "Sam & Jo", left: 18, allowance: 36, endsIn: 8 * 3600 + 60),
    .init(event: "Sam & Jo", left: 6, allowance: 36, endsIn: 40 * 60),
    .init(event: "Sam & Jo", left: 1, allowance: 36, endsIn: 95),
    .init(event: "Sam & Jo", left: 0, allowance: 36, endsIn: 5 * 60),
    .init(event: "Priya and engagement", left: -1, allowance: -1, endsIn: 3 * 3600 + 60),
    .init(event: "The Very Long Wedding of Priya and Alexander", left: 24, allowance: 36, endsIn: 2 * 3600 + 60),
]

private struct Root: View {
    var body: some View {
        ScrollView {
            VStack(spacing: 18) {
                ForEach(cases) { c in
                    StillsLockScreenCard(
                        eventName: c.event,
                        photosLeft: c.left,
                        allowance: c.allowance,
                        endTime: Date().addingTimeInterval(c.endsIn),
                        cameraDestination: nil
                    )
                    .background(Ink.background)
                    // The system container's radius, so the footer clips into
                    // the bottom corners as it will on the lock screen.
                    .clipShape(RoundedRectangle(cornerRadius: 26, style: .continuous))
                }
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 28)
        }
        .background(Color.black.ignoresSafeArea())
    }
}

@main
struct PreviewApp: App {
    var body: some Scene { WindowGroup { Root().preferredColorScheme(.dark) } }
}
SWIFT

cat > "$APP/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>StillsLAPreview</string>
  <key>CFBundleDisplayName</key><string>LA Preview</string>
  <key>CFBundleIdentifier</key><string>com.potoevents.stillslapreview</string>
  <key>CFBundleExecutable</key><string>StillsLAPreview</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleSupportedPlatforms</key><array><string>iPhoneSimulator</string></array>
  <key>MinimumOSVersion</key><string>16.2</string>
  <key>UIDeviceFamily</key><array><integer>1</integer></array>
  <key>LSRequiresIPhoneOS</key><true/>
  <key>UILaunchScreen</key><dict/>
  <key>UIAppFonts</key>
  <array>
    <string>CormorantGaramond-SemiBold.ttf</string>
    <string>InstrumentSans-Regular.ttf</string>
    <string>InstrumentSans-Medium.ttf</string>
  </array>
</dict></plist>
PLIST

xcrun swiftc -parse-as-library \
  -sdk "$(xcrun --sdk iphonesimulator --show-sdk-path)" \
  -target arm64-apple-ios16.2-simulator \
  -o "$APP/StillsLAPreview" \
  "$WORK/main.swift" "$CARD" 2>&1 | grep -v "incompatible-sysroot" || true

if [ ! -x "$APP/StillsLAPreview" ]; then
  echo "Build failed." >&2
  exit 1
fi

echo "→ Installing…"
xcrun simctl terminate booted "$BUNDLE_ID" >/dev/null 2>&1 || true
xcrun simctl install booted "$APP"
xcrun simctl launch booted "$BUNDLE_ID" >/dev/null
echo "✓ Live Activity card on the simulator."
